# Generated by Django 5.0.6 on 2024-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
