# Generated by Django 4.2.16 on 2024-09-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_remove_complainttable_date_remove_feedbacktable_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtable',
            name='Subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
