# Generated by Django 4.2.16 on 2024-10-01 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0006_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='Place',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='Post',
        ),
    ]
