# Generated by Django 4.2.16 on 2024-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_rename_place_usertable_address_remove_usertable_pin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='Address',
            new_name='Place',
        ),
        migrations.AddField(
            model_name='usertable',
            name='Pin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='Post',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
