# Generated by Django 4.2.16 on 2024-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_rename_address_usertable_place_usertable_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='Password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
