# Generated by Django 4.2.16 on 2024-10-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0010_logintable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='Rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
